export enum BlockType {
  Air = 0,
  Grass,
  Dirt,
  Stone,
  Sand,
  Wood,
  Leaves,
  Water,
  // Extended block types
  Bedrock = 8,
  CoalOre,
  IronOre,
  GoldOre,
  DiamondOre,
  RedstoneOre,
  LapisOre,
  EmeraldOre,
  QuartzOre,
  // Stone variants
  Cobblestone,
  StoneBricks,
  Deepslate,
  // Nether blocks
  Netherrack,
  SoulSand,
  SoulSoil,
  Basalt,
  Blackstone,
  CrimsonNylium,
  WarpedNylium,
  NetherGoldOre,
  NetherQuartzOre,
  AncientDebris,
  // End blocks
  EndStone,
  EndStoneBricks,
  PurpurBlock,
  ChorusPlant,
  ChorusFlower,
  // Utility blocks
  Glass,
  TNT,
  Bookshelf,
  CraftingTable,
  Furnace,
  Chest,
  // Plants
  TallGrass,
  Fern,
  DeadBush,
  Cactus,
  SugarCane,
  Kelp,
  Seagrass,
  // Flowers
  Dandelion,
  Poppy,
  BlueOrchid,
  Allium,
  AzureBluet,
  RedTulip,
  OrangeTulip,
  WhiteTulip,
  PinkTulip,
  OxeyeDaisy,
  Cornflower,
  LilyOfTheValley,
  WitherRose,
  // Crops
  Wheat,
  Carrots,
  Potatoes,
  Beetroots,
  // Mushrooms
  BrownMushroom,
  RedMushroom,
  // Vines/Ladders
  Vine,
  Ladder,
  // Rails
  Rail,
  PoweredRail,
  DetectorRail,
  ActivatorRail,
  // Redstone
  RedstoneWire,
  RedstoneTorch,
  RedstoneBlock,
  RedstoneRepeater,
  RedstoneComparator,
  // Pistons
  Piston,
  StickyPiston,
  // Doors
  OakDoor,
  IronDoor,
  // Pressure plates/buttons
  StonePressurePlate,
  WoodenPressurePlate,
  StoneButton,
  WoodenButton,
  // Trapdoors
  OakTrapdoor,
  IronTrapdoor,
  // Fences/Gates
  OakFence,
  OakFenceGate,
  // Walls
  CobblestoneWall,
  // Stairs/Slabs
  StoneStairs,
  StoneSlab,
  // Lanterns
  Lantern,
  SoulLantern,
  // Glowstone/Shroomlight
  Glowstone,
  Shroomlight,
  // Sea lantern
  SeaLantern,
  // Conduit
  Conduit,
  // Beacon
  Beacon,
  // Enchanting
  EnchantingTable,
  // Anvil
  Anvil,
  // Grindstone
  Grindstone,
  // Smithing
  SmithingTable,
  // Stonecutter
  Stonecutter,
  // Loom
  Loom,
  // Cartography
  CartographyTable,
  // Composter
  Composter,
  // Barrel
  Barrel,
  // Blast furnace
  BlastFurnace,
  // Smoker
  Smoker,
  // Campfire
  Campfire,
  SoulCampfire,
  // Target
  Target,
  // Lightning rod
  LightningRod,
  // Copper
  CopperBlock,
  ExposedCopper,
  WeatheredCopper,
  OxidizedCopper,
  WaxedCopperBlock,
  WaxedExposedCopper,
  WaxedWeatheredCopper,
  WaxedOxidizedCopper,
  // Amethyst
  AmethystBlock,
  BuddingAmethyst,
  AmethystCluster,
  // Calcite/Tuff
  Calcite,
  Tuff,
  // Dripstone
  DripstoneBlock,
  PointedDripstone,
  // Sculk
  Sculk,
  SculkVein,
  SculkCatalyst,
  SculkShrieker,
  SculkSensor,
  // Mud
  Mud,
  PackedMud,
  MudBricks,
  // Mangrove
  MangroveRoots,
  MuddyMangroveRoots,
  // Reinforced deepslate
  ReinforcedDeepslate,
}

export const BLOCK_NAMES: Record<BlockType, string> = {
  [BlockType.Air]: 'Air',
  [BlockType.Grass]: 'Grass Block',
  [BlockType.Dirt]: 'Dirt',
  [BlockType.Stone]: 'Stone',
  [BlockType.Sand]: 'Sand',
  [BlockType.Wood]: 'Oak Log',
  [BlockType.Leaves]: 'Oak Leaves',
  [BlockType.Water]: 'Water',
  [BlockType.Bedrock]: 'Bedrock',
  [BlockType.CoalOre]: 'Coal Ore',
  [BlockType.IronOre]: 'Iron Ore',
  [BlockType.GoldOre]: 'Gold Ore',
  [BlockType.DiamondOre]: 'Diamond Ore',
  [BlockType.RedstoneOre]: 'Redstone Ore',
  [BlockType.LapisOre]: 'Lapis Lazuli Ore',
  [BlockType.EmeraldOre]: 'Emerald Ore',
  [BlockType.QuartzOre]: 'Nether Quartz Ore',
  [BlockType.Cobblestone]: 'Cobblestone',
  [BlockType.StoneBricks]: 'Stone Bricks',
  [BlockType.Deepslate]: 'Deepslate',
  [BlockType.Netherrack]: 'Netherrack',
  [BlockType.SoulSand]: 'Soul Sand',
  [BlockType.SoulSoil]: 'Soul Soil',
  [BlockType.Basalt]: 'Basalt',
  [BlockType.Blackstone]: 'Blackstone',
  [BlockType.CrimsonNylium]: 'Crimson Nylium',
  [BlockType.WarpedNylium]: 'Warped Nylium',
  [BlockType.NetherGoldOre]: 'Nether Gold Ore',
  [BlockType.NetherQuartzOre]: 'Nether Quartz Ore',
  [BlockType.AncientDebris]: 'Ancient Debris',
  [BlockType.EndStone]: 'End Stone',
  [BlockType.EndStoneBricks]: 'End Stone Bricks',
  [BlockType.PurpurBlock]: 'Purpur Block',
  [BlockType.ChorusPlant]: 'Chorus Plant',
  [BlockType.ChorusFlower]: 'Chorus Flower',
  [BlockType.Glass]: 'Glass',
  [BlockType.TNT]: 'TNT',
  [BlockType.Bookshelf]: 'Bookshelf',
  [BlockType.CraftingTable]: 'Crafting Table',
  [BlockType.Furnace]: 'Furnace',
  [BlockType.Chest]: 'Chest',
  [BlockType.TallGrass]: 'Tall Grass',
  [BlockType.Fern]: 'Fern',
  [BlockType.DeadBush]: 'Dead Bush',
  [BlockType.Cactus]: 'Cactus',
  [BlockType.SugarCane]: 'Sugar Cane',
  [BlockType.Kelp]: 'Kelp',
  [BlockType.Seagrass]: 'Seagrass',
  [BlockType.Dandelion]: 'Dandelion',
  [BlockType.Poppy]: 'Poppy',
  [BlockType.BlueOrchid]: 'Blue Orchid',
  [BlockType.Allium]: 'Allium',
  [BlockType.AzureBluet]: 'Azure Bluet',
  [BlockType.RedTulip]: 'Red Tulip',
  [BlockType.OrangeTulip]: 'Orange Tulip',
  [BlockType.WhiteTulip]: 'White Tulip',
  [BlockType.PinkTulip]: 'Pink Tulip',
  [BlockType.OxeyeDaisy]: 'Oxeye Daisy',
  [BlockType.Cornflower]: 'Cornflower',
  [BlockType.LilyOfTheValley]: 'Lily of the Valley',
  [BlockType.WitherRose]: 'Wither Rose',
  [BlockType.Wheat]: 'Wheat',
  [BlockType.Carrots]: 'Carrots',
  [BlockType.Potatoes]: 'Potatoes',
  [BlockType.Beetroots]: 'Beetroots',
  [BlockType.BrownMushroom]: 'Brown Mushroom',
  [BlockType.RedMushroom]: 'Red Mushroom',
  [BlockType.Vine]: 'Vine',
  [BlockType.Ladder]: 'Ladder',
  [BlockType.Rail]: 'Rail',
  [BlockType.PoweredRail]: 'Powered Rail',
  [BlockType.DetectorRail]: 'Detector Rail',
  [BlockType.ActivatorRail]: 'Activator Rail',
  [BlockType.RedstoneWire]: 'Redstone Dust',
  [BlockType.RedstoneTorch]: 'Redstone Torch',
  [BlockType.RedstoneBlock]: 'Redstone Block',
  [BlockType.RedstoneRepeater]: 'Redstone Repeater',
  [BlockType.RedstoneComparator]: 'Redstone Comparator',
  [BlockType.Piston]: 'Piston',
  [BlockType.StickyPiston]: 'Sticky Piston',
  [BlockType.OakDoor]: 'Oak Door',
  [BlockType.IronDoor]: 'Iron Door',
  [BlockType.StonePressurePlate]: 'Stone Pressure Plate',
  [BlockType.WoodenPressurePlate]: 'Wooden Pressure Plate',
  [BlockType.StoneButton]: 'Stone Button',
  [BlockType.WoodenButton]: 'Wooden Button',
  [BlockType.OakTrapdoor]: 'Oak Trapdoor',
  [BlockType.IronTrapdoor]: 'Iron Trapdoor',
  [BlockType.OakFence]: 'Oak Fence',
  [BlockType.OakFenceGate]: 'Oak Fence Gate',
  [BlockType.CobblestoneWall]: 'Cobblestone Wall',
  [BlockType.StoneStairs]: 'Stone Stairs',
  [BlockType.StoneSlab]: 'Stone Slab',
  [BlockType.Lantern]: 'Lantern',
  [BlockType.SoulLantern]: 'Soul Lantern',
  [BlockType.Glowstone]: 'Glowstone',
  [BlockType.Shroomlight]: 'Shroomlight',
  [BlockType.SeaLantern]: 'Sea Lantern',
  [BlockType.Conduit]: 'Conduit',
  [BlockType.Beacon]: 'Beacon',
  [BlockType.EnchantingTable]: 'Enchanting Table',
  [BlockType.Anvil]: 'Anvil',
  [BlockType.Grindstone]: 'Grindstone',
  [BlockType.SmithingTable]: 'Smithing Table',
  [BlockType.Stonecutter]: 'Stonecutter',
  [BlockType.Loom]: 'Loom',
  [BlockType.CartographyTable]: 'Cartography Table',
  [BlockType.Composter]: 'Composter',
  [BlockType.Barrel]: 'Barrel',
  [BlockType.BlastFurnace]: 'Blast Furnace',
  [BlockType.Smoker]: 'Smoker',
  [BlockType.Campfire]: 'Campfire',
  [BlockType.SoulCampfire]: 'Soul Campfire',
  [BlockType.Target]: 'Target',
  [BlockType.LightningRod]: 'Lightning Rod',
  [BlockType.CopperBlock]: 'Block of Copper',
  [BlockType.ExposedCopper]: 'Exposed Copper',
  [BlockType.WeatheredCopper]: 'Weathered Copper',
  [BlockType.OxidizedCopper]: 'Oxidized Copper',
  [BlockType.WaxedCopperBlock]: 'Waxed Block of Copper',
  [BlockType.WaxedExposedCopper]: 'Waxed Exposed Copper',
  [BlockType.WaxedWeatheredCopper]: 'Waxed Weathered Copper',
  [BlockType.WaxedOxidizedCopper]: 'Waxed Oxidized Copper',
  [BlockType.AmethystBlock]: 'Block of Amethyst',
  [BlockType.BuddingAmethyst]: 'Budding Amethyst',
  [BlockType.AmethystCluster]: 'Amethyst Cluster',
  [BlockType.Calcite]: 'Calcite',
  [BlockType.Tuff]: 'Tuff',
  [BlockType.DripstoneBlock]: 'Dripstone Block',
  [BlockType.PointedDripstone]: 'Pointed Dripstone',
  [BlockType.Sculk]: 'Sculk',
  [BlockType.SculkVein]: 'Sculk Vein',
  [BlockType.SculkCatalyst]: 'Sculk Catalyst',
  [BlockType.SculkShrieker]: 'Sculk Shrieker',
  [BlockType.SculkSensor]: 'Sculk Sensor',
  [BlockType.Mud]: 'Mud',
  [BlockType.PackedMud]: 'Packed Mud',
  [BlockType.MudBricks]: 'Mud Bricks',
  [BlockType.MangroveRoots]: 'Mangrove Roots',
  [BlockType.MuddyMangroveRoots]: 'Muddy Mangrove Roots',
  [BlockType.ReinforcedDeepslate]: 'Reinforced Deepslate',
};